#! /bin/bash
set -e

package_dir=VAR_PACKAGE_DIR
compiler=VAR_COMPILER

case "$1" in
    remove|upgrade|deconfigure)
	update-alternatives --quiet --remove diablo-$compiler-toolchain /opt/diablo-toolchains/$package_dir
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
exit 0


